from shifts.employee import Employee

EMPLOYEES = [
        Employee(
            name='Maslow',
            hebrew_names='מסלו',
            available_from='2024-12-26',
            is_manager=True,
        ),
        Employee(
            name='Madmoni',
            hebrew_names='מדמוני',
            available_from='2024-12-26',
            is_manager=True,
        ),
        Employee(
            name='Rosen',
            hebrew_names='רוזן',
            available_from='2024-12-26',
        ),
        Employee(
            name='Aghion',
            hebrew_names='אגיון',
            available_from='2024-12-26',
        ),
        Employee(
            name='Sivan',
            hebrew_names='סיוון',
            available_from='2024-12-26',
        ),
        Employee(
            name='Tobiana',
            hebrew_names='טוביאנה',
            available_from='2024-12-26',
            preferred_shift_partner='Pinhas',
        ),
        Employee(
            name='Turjeman',
            hebrew_names=['תורגמן', "תורג'מן"],
            available_from='2024-12-26',
            min_consecutive_home_days=7,
        ),
        Employee(
            name='Oz',
            hebrew_names='עוז',
            available_from='2024-12-26',
        ),
        Employee(
            name='Pavel',
            hebrew_names='פבל',
            available_from='2024-12-26',
        ),
        Employee(
            name='Rahamim',
            hebrew_names='רחמים',
            available_from='2025-01-15',
        ),
        Employee(
            name='Pinhas',
            hebrew_names='פנחס',
            available_from='2024-12-26',
        ),
        Employee(
            name='Elior',
            hebrew_names='אליאור',
            available_from='2024-12-26',
        ),
        Employee(
            name='Shushan',
            hebrew_names='שושן',
            available_from='2024-12-26',
        ),
        Employee(
            name='Ron',
            hebrew_names='רון',
            available_from='2024-12-26',
        )
    ]